### ISSUE TITLE
Good use of media resizing

### ISSUE THREAD

**Issue by sangjunp4rk** [maning83/Capstone#3]
Great incorporation of mobile resizing! Though it may seem tedious, it is an incredibly important concept since screen sizes vary tremendously today and it’s important that you website looks exactly as you design it to. Great job!

https://github.com/maning83/Capstone/blob/master/Resource/style.css#L155

**Comment by maning83** [comment]
Thank you. I do see the complexity of web building as the dynamics keep developing.
